# File paths
PATH_RESOURCE = "./resources"
PATH_IMAGE = f"{PATH_RESOURCE}/images"
PATH_FONT = f"{PATH_RESOURCE}/fonts"

PATH_DATA = "./data"
PATH_LOG = f"{PATH_DATA}/logs"
PATH_CONFIG = f"{PATH_DATA}/configs"
PATH_GAME = f"{PATH_DATA}/games"

# GUI
GUI_WIDTH = 1920
GUI_HEIGHT = 1080
GUI_FPS = 30

FPS_LOG = False
SHOW_FPS_DEFAULT = False

# User
DEFAULT_TIME = 300
TIME_RESET_TIMEOUT = 1000

AUTO_UPDATE = 300
FAST_UPDATE = 22

SHOW_USERS_IN_DEBUG_SCREEN = True
